version: "3.7"
services:
    db: 
        build: "./APP.Data"
        image: mysql
        command: --default-authentication-plugin=mysql_native_password
        restart: always
        ports:
            - 3307:3306
        # environment:
        #     MYSQL_ROOT_PASSWORD: mudar123
        volumes:
             - C:/MYSQL_DATA/volumes:/var/lib/mysql

    ADMINER:
        image: adminer
        restart: always
        ports:
            - 8888:8080

    api:
        build: .
        image: todoapi
        restart: always
        # environment: 
        #     DB_HOST: db
        #     DB_DATABASE: todoapi
        #     DB_USERNAME: root
        #     DB_PASSWORD: mudar123
        #     DB_PORT: 3307
        ports:
            - 80:80
            - 443:443
        depends_on: 
            - db
        links:
            - db