version: "3.7"
services:
  db:
    build: "./APP.Data"
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - 3307:3306
    volumes:
      - C:/MYSQL_DATA/volumes:/var/lib/mysql
    networks:
      testing_net:
        ipv4_address: 172.28.1.5

  adminer:
    image: adminer
    restart: always
    ports:
      - 8888:8080
    networks:
      testing_net:
        ipv4_address: 172.28.1.8

  api:
    build: .
    image: todoapi
    restart: always
    # environment:
    #   - DB_HOST='172.28.1.5'
    #   - DB_DATABASE='todoapp'
    #   - DB_USERNAME='root'
    #   - DB_PASSWORD='mudar123'
    #   - DB_PORT='3306'
    ports:
      - 80:80
      - 443:443
    depends_on:
      - db
    links:
      - db
    networks:
      testing_net:
        ipv4_address: 172.28.1.10

networks:
  testing_net:
    ipam:
      driver: default
      config:
        - subnet: 172.28.0.0/16
